version: '1'
services:
  api:
    image: ecommerce-cms-api:latest
    ports:
      - "7275:80"
    depends_on:
      - db
  ui:
    image: ecommerce-cms-ui:latest
    ports:
      - "4200:80"
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1488:1433"
    environment:
      SA_PASSWORD: "Gfhjkm123321"
      ACCEPT_EULA: "Y"
    volumes:
      - sqldata:/var/opt/mssql
  
volumes:
  sqldata: